### PR TITLE
fix: Documentation: version number and usage

### LINKED ISSUE #91: Documentation errors in README and Javadoc
The README uses an old version, but 0.117.0 is available.

The example configurations are a bit hard to read because:
* The comments are at different locations.
* Javadoc uses a list instead of a code block.

The Javadoc incorrectly states that there is a `level` tag that can be used to filter, but you have to use a `filter` tag (as is correctly shown in the README).

### PR DESCRIPTION
**Pull request by jstuyts**
fix: Documentation: version number and usage

Updated version number to latest release.

Improved documentation:
- Synced Javadoc and `README.md`, correcting error about filter in Javadoc
- Made example in Javadoc more easy to read and copy

Made 2 fields final to prevent editor/compiler warning.

Fixes #91

### CODE REVIEW

**Comment by jstuyts** [comment]
@googlebot I signed it!

**Comment by kolea2** [comment]
Hi @jstuyts, thanks for your patience - I believe this issue should be fixed. Can you try rerunning your presubmit checks?

**Comment by jstuyts** [comment]
I spent 10 minutes trying to find the rerun button or command, but I cannot find it.

**Comment by kolea2** [comment]
@jstuyts I was able to rerun them! If you go under the 'Checks' tab, click on 'ci' and one of the builds, and rerun is in the top right corner. Unfortunately, it looks like it's still failing. @chingor13 can you help take a look here?

**Pull request merged**
